{% set name = "ophyd" %}
{% set version = "1.4.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/{{ name }}/archive/v{{ version }}.tar.gz
  fn: {{ name }}-v{{ version }}.tar.gz

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - networkx
    - numpy
    - pyepics
    - python

test:
  requires:
    - pytest
    - pyepics
  imports:
    - {{ name }}
  commands:
    - pytest --pyargs {{ name }}.tests -k pyepics

about:
  home: https://github.com/bluesky/{{ name }}
  license: BSD 3-Clause
  summary: 'Ophyd - EPICS Client Abstractions'
