{% set version = "1.4.0rc1" %}

package:
    name: ophyd
    version: {{ version }}

source:
    url: https://github.com/NSLS-II/ophyd/archive/v{{ version }}.tar.gz
    fn: ophyd-v{{ version }}.tar.gz

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"
    skip: True  # [py<36]

requirements:
    build:
        - python
        - pip
    run:
        - networkx
        - numpy
        - pyepics
        - python

test:
    imports:
        - ophyd

about:
    home: https://github.com/bluesky/ophyd
    license: BSD 3-Clause
