{% set name = "ophyd" %}
{% set version = "1.4.0rc5" %}
{% set sha256 = "dcf7f07274628a17331c4cf41379220ddc4cbd35f69bf06072da2d598ac13e11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - networkx
    - numpy
    - pyepics

test:
  imports:
    - {{ name }}
    - {{ name }}.utils
    - {{ name }}.areadetector
    - {{ name }}.sim

about:
  home: https://blueskyproject.io
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Ophyd - EPICS Client Abstractions'
  description: 'Ophyd - EPICS Client Abstractions'
  doc_url: https://blueskyproject.io/ophyd
  dev_url: https://github.com/bluesky/ophyd
