{% set name = "ophyd" %}
{% set version = "1.3.3" %}
{% set sha256 = "1526e5e934b4c85a9d51f822e69ac45913f308043221abd0316b922350034cbf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/{{ name }}/archive/v{{ version }}.tar.gz
  fn: {{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - networkx
    - numpy
    - pyepics

test:
  imports:
    - {{ name }}
    - {{ name }}.utils
    - {{ name }}.areadetector
    - {{ name }}.sim

about:
  home: https://github.com/bluesky/{{ name }}
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Ophyd - EPICS Client Abstractions'

extra:
  recipe-maintainers:
    - CJ-Wright
    - conda-forge/event-model
